aliases:
  - &restore-cache
    keys:
      - v2-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
      # Fallback in case checksum fails
      - v2-dependencies-{{ .Branch }}-

  - &save-cache
    paths:
      - node_modules
      - website/node_modules
    key: v2-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}

version: 2
jobs:
  test-node-10:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: npm install
      - save-cache: *save-cache
      - run:
          command: npm test

  test-node-8.3:
    docker:
      - image: circleci/node:8.3
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: npm install
      - save-cache: *save-cache
      - run:
          command: npm test

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test-node-8.3
      - test-node-10
